# Generated by Django 4.2 on 2023-04-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('facility_items', models.ManyToManyField(to='ish.facilityitem')),
            ],
        ),
    ]
