# Generated by Django 4.2 on 2023-04-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ish', '0003_facilitycategory_alter_facilitygroup_facility_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitygroup',
            name='facility_items',
        ),
        migrations.AddField(
            model_name='facilitygroup',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ish.facilitycategory'),
        ),
    ]
