# Generated by Django 4.2 on 2023-04-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('author', models.TextField()),
                ('inStock', models.BooleanField(default=True)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
